version: "3.8"

services:
  php:
    build: .
    container_name: php-portfolio
    volumes:
      - ./public:/var/www/html
      - ./app:/var/www/app
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-portfolio
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: livraria
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-portfolio
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
